### ISSUE TITLE
KeyError: 'assets' issues

### ISSUE THREAD

**Issue by lpc-eol** [bharath5673/StrongSORT-YOLO#1]
Traceback (most recent call last):
  File "/home/student/cql/t/yolov7/utils/google_utils.py", line 26, in attempt_download
    assets = [x['name'] for x in response['assets']]  # release assets
KeyError: 'assets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/student/cql/t/track_v7.py", line 382, in <module>
    detect()
  File "/home/student/cql/t/track_v7.py", line 90, in detect
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "/home/student/cql/t/yolov7/models/experimental.py", line 87, in attempt_load
    attempt_download(w)
  File "/home/student/cql/t/yolov7/utils/google_utils.py", line 30, in attempt_download
    tag = subprocess.check_output('git tag', shell=True).decode().split()[-1]
IndexError: list index out of range

Process finished with exit code 1

Thank you for your help.

**Comment by bharath5673** [comment]
> Traceback (most recent call last): File "/home/student/cql/t/yolov7/utils/google_utils.py", line 26, in attempt_download assets = [x['name'] for x in response['assets']] # release assets KeyError: 'assets'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/student/cql/t/track_v7.py", line 382, in detect() File "/home/student/cql/t/track_v7.py", line 90, in detect model = attempt_load(weights, map_location=device) # load FP32 model File "/home/student/cql/t/yolov7/models/experimental.py", line 87, in attempt_load attempt_download(w) File "/home/student/cql/t/yolov7/utils/google_utils.py", line 30, in attempt_download tag = subprocess.check_output('git tag', shell=True).decode().split()[-1] IndexError: list index out of range
> 
> Process finished with exit code 1
> 
> Thank you for your help.

hi... 
there is little problem with Paths and Downloads for weights in YOLOv7 api itself.. 
dont try with absolute paths of weights... 

```
 /// cd into StrongSORT-YOLO just try as it is below
python track_v7.py  --yolo-weights weights/yolov7-tiny.pt  --source test.mp4 
```

incase of custom weights ??? ..place them inside the StrongSORT-YOLO/weights and try calling them the same..

**Comment by lpc-eol** [comment]
Fixed with thx
