### ISSUE TITLE
dynamic id assignment

### ISSUE THREAD

**Issue by faizan1234567** [bharath5673/StrongSORT-YOLO#18]
How can I dynamically assign id to an object based on a meeting a condition, for example, if object A was assign with id 5, but upon certain condition i want to change it to 3 or some other number, how can i modify code to do it?

**Comment by bharath5673** [comment]
Simple.. Appy with if condition

**Comment by faizan1234567** [comment]
how, could you write an example please? I have been stuch here

**Comment by bharath5673** [comment]
If A == 5:
  A=3

**Comment by faizan1234567** [comment]
ok I will try, I think we need to overwrite the tracker.track_id attribute in tracker class. But i am not sure, how can i do in in track_v5.py file.
