### ISSUE TITLE
failure for Filter tracked classes

### ISSUE THREAD

**Issue by lpc-eol** [bharath5673/StrongSORT-YOLO#2]
I try to track a single class by modifying 
python track_v7.py --source ex1_video_1.mp4 --yolo-weights weights/yolov7x.pt --classes 32

![image](https://user-images.githubusercontent.com/76684848/182785394-37a040cc-16a0-4e9d-9edb-87974ab03424.png)

I found that the output of the video still contains multiple classes.
Thank you for your help.

**Comment by bharath5673** [comment]
> 

which multiple classes ?

**Comment by lpc-eol** [comment]
![image](https://user-images.githubusercontent.com/76684848/182788809-3470c503-08ad-453e-98f4-e7515dbfe5c0.png)
The output shows the tracker tracking all classes in coco datasets

which is different to the printing result.
![image](https://user-images.githubusercontent.com/76684848/182789092-63a36377-2e57-49b2-af30-a5b0949bf148.png)

python track_v7.py --source ex1_video_1.mp4 --yolo-weigh     ts weights/yolov7x.pt --classes 32
this is the command I used.

**Comment by lpc-eol** [comment]
Suppose you did not find the same problem in your testing. I will fix the problem on my own. Thank you.

**Comment by bharath5673** [comment]
> Suppose you did not find the same problem in your testing. I will fix the problem on my own. Thank you.

Fir Sure u can
