### ISSUE TITLE
Real-time multi-camera

### ISSUE THREAD

**Issue by epigraphe** [bharath5673/StrongSORT-YOLO#21]
Hello
The description says Real-time multi-camera
How does multicam work? I didn't find this in the description.
Thank you

**Comment by bharath5673** [comment]
hi @epigraphe ,, now u can find it @[ track_v8.py](https://github.com/bharath5673/StrongSORT-YOLO/blob/main/track_v8.py) //
to make it work for multiple cameras, run `python  track_v8_2.py  --sources  test1.webm   test2.mp4   0 `
