### ISSUE TITLE
Real-time multi-camera Tracking is not showing

### ISSUE THREAD

**Issue by Razamalik4497** [bharath5673/StrongSORT-YOLO#23]
Hello Bharath, I appreciate your efforts in Yolo detection & tracking but I'm unable to get anything about multicamera tracking MCT. Can you please point me to that code where I can find the MCT stuff? thanks

**Comment by bharath5673** [comment]
hi @Razamalik4497 .. now its updated.. [ now u can try ](https://github.com/bharath5673/StrongSORT-YOLO?tab=readme-ov-file#yolov8-counter-)

```
$ python track_v8.py --source 0 1 vid1.mp4 vid2.mp4 --track --count

```

**Comment by Razamalik4497** [comment]
Thank you, Bharath, for your invaluable assistance. I have successfully implemented multi-camera tracking. However, I've encountered an issue: the tracking IDs differ between both streams, even though I used two cameras capturing the same object simultaneously. 

Thank you!
Raza

**Comment by bharath5673** [comment]
> Thank you, Bharath, for your invaluable assistance. I have successfully implemented multi-camera tracking. However, I've encountered an issue: the tracking IDs differ between both streams, even though I used two cameras capturing the same object simultaneously.
> 
> Thank you! Raza

oh .. i got you... i think u are searching for this ['Multi-target Multi-camera tracking'](https://www.youtube.com/watch?v=sroLfpX4F0w&ab_channel=MhttxHe) // even nvidia has done the same like[ 'Tracking Objects Across Multiple Cameras Made Easy with Metropolis Microservices'](https://www.youtube.com/watch?v=oBL84CeLwKk&ab_channel=NVIDIADeveloper) /// hope this helps ))

**Comment by Razamalik4497** [comment]
I appreciate your prompt response. 
After reviewing the 'NVIDIA Multi-Camera Tracking,' I realized that I want to use YOLO for my project since it's already written in YOLO. This will make it easier to implement multi-camera tracking using YOLO. Can I enhance the code to track the same object with same ID in your multi camera tracking.
