### ISSUE TITLE
Unknown model

### ISSUE THREAD

**Issue by marioRaouf** [bharath5673/StrongSORT-YOLO#4]
when running the command : python track_v7.py --source test_inputs\chase.mp4 --yolo-weights weights/yolov7-tiny.pt --img 640
I get the below error:
YOLOR  v0.1-3-g9ee1835 torch 1.12.1+cpu CPU

Fusing layers...
Model Summary: 200 layers, 6219709 parameters, 229245 gradients
Traceback (most recent call last):
  File "yolov5_yolov7_tracking\track_v7.py", line 378, in <module>
    detect()
  File "yolov5_yolov7_tracking\track_v7.py", line 124, in detect
    StrongSORT(
  File "yolov5_yolov7_tracking\strong_sort\strong_sort.py", line 40, in __init__
    self.extractor = FeatureExtractor(
  File "yolov5_yolov7_tracking\strong_sort/deep/reid\torchreid\utils\feature_extractor.py", line 71, in __init__
    model = build_model(
  File "yolov5_yolov7_tracking\strong_sort/deep/reid\torchreid\models\__init__.py", line 114, in build_model
    raise KeyError(
KeyError: "Unknown model: None. Must be one of ['resnet18', 'resnet34', 'resnet50', 'resnet101', 'resnet152', 'resnext50_32x4d', 'resnext101_32x8d', 'resnet50_fc512', 'se_resnet50', 'se_resnet50_fc512', 'se_resnet101', 'se_resnext50_32x4d', 'se_resnext101_32x4d', 'densenet121', 'densenet169', 'densenet201', 'densenet161', 'densenet121_fc512', 'inceptionresnetv2', 'inceptionv4', 'xception', 'resnet50_ibn_a', 'resnet50_ibn_b', 'nasnsetmobile', 'mobilenetv2_x1_0', 'mobilenetv2_x1_4', 'shufflenet', 'squeezenet1_0', 'squeezenet1_0_fc512', 'squeezenet1_1', 'shufflenet_v2_x0_5', 'shufflenet_v2_x1_0', 'shufflenet_v2_x1_5', 'shufflenet_v2_x2_0', 'mudeep', 'resnet50mid', 'hacnn', 'pcb_p6', 'pcb_p4', 'mlfn', 'osnet_x1_0', 'osnet_x0_75', 'osnet_x0_5', 'osnet_x0_25', 'osnet_ibn_x1_0', 'osnet_ain_x1_0', 'osnet_ain_x0_75', 'osnet_ain_x0_5', 'osnet_ain_x0_25']"

**Comment by bharath5673** [comment]
> when running the command : python track_v7.py --source test_inputs\chase.mp4 --yolo-weights weights/yolov7-tiny.pt --img 640 I get the below error: YOLOR v0.1-3-g9ee1835 torch 1.12.1+cpu CPU
> 
> Fusing layers... Model Summary: 200 layers, 6219709 parameters, 229245 gradients Traceback (most recent call last): File "yolov5_yolov7_tracking\track_v7.py", line 378, in detect() File "yolov5_yolov7_tracking\track_v7.py", line 124, in detect StrongSORT( File "yolov5_yolov7_tracking\strong_sort\strong_sort.py", line 40, in **init** self.extractor = FeatureExtractor( File "yolov5_yolov7_tracking\strong_sort/deep/reid\torchreid\utils\feature_extractor.py", line 71, in **init** model = build_model( File "yolov5_yolov7_tracking\strong_sort/deep/reid\torchreid\models__init__.py", line 114, in build_model raise KeyError( KeyError: "Unknown model: None. Must be one of ['resnet18', 'resnet34', 'resnet50', 'resnet101', 'resnet152', 'resnext50_32x4d', 'resnext101_32x8d', 'resnet50_fc512', 'se_resnet50', 'se_resnet50_fc512', 'se_resnet101', 'se_resnext50_32x4d', 'se_resnext101_32x4d', 'densenet121', 'densenet169', 'densenet201', 'densenet161', 'densenet121_fc512', 'inceptionresnetv2', 'inceptionv4', 'xception', 'resnet50_ibn_a', 'resnet50_ibn_b', 'nasnsetmobile', 'mobilenetv2_x1_0', 'mobilenetv2_x1_4', 'shufflenet', 'squeezenet1_0', 'squeezenet1_0_fc512', 'squeezenet1_1', 'shufflenet_v2_x0_5', 'shufflenet_v2_x1_0', 'shufflenet_v2_x1_5', 'shufflenet_v2_x2_0', 'mudeep', 'resnet50mid', 'hacnn', 'pcb_p6', 'pcb_p4', 'mlfn', 'osnet_x1_0', 'osnet_x0_75', 'osnet_x0_5', 'osnet_x0_25', 'osnet_ibn_x1_0', 'osnet_ain_x1_0', 'osnet_ain_x0_75', 'osnet_ain_x0_5', 'osnet_ain_x0_25']"

this should not happen,, may be some venv issue..( with pytorch libs)  // please try witj new venv
