### ISSUE TITLE
vehicle_side in annotation file

### ISSUE THREAD

**Issue by bit-scientist** [bharath5673/StrongSORT-YOLO#5]
First of all, thank you for the work you have done, it's quite helpful.

In `track_v5.py` you defined `vehicle_side` as `0` for left and `1` for right side of the vehicle, right? I have a couple of questions regarding this.

1. What does `vehicle_side` imply here?
    I could see that 0 (left side) is assigned if the `bbox_right` is smaller than the half of `frame_width`. I don't think it applies to all cases. In my demo video, a vehicle with id1 is coming from top-left towards bottom right at an intersection. The txt file for this vehicle assigned 0 (left side), but the **visible** `vehicle_side` is right. Can you explain it a little more?
2. Why could one need to know the `vehicle side` in general?

Thank you.

**Comment by bharath5673** [comment]
that was some experimental..!! // and not got general // ty
