### ISSUE TITLE
Object Path Trajectory 

### ISSUE THREAD

**Issue by MAli-Farooq** [bharath5673/StrongSORT-YOLO#7]
Hi,

Can someone help me with how we can update the code track.py (both for v5 and v7) to show the moving object path trajectory as shown in below video link rather than just assigning the unique numbers to each object?

https://www.youtube.com/watch?v=5sya7sl9wWc

Thank you

**Comment by bharath5673** [comment]
> Hi,
> 
> Can someone help me with how we can update the code track.py (both for v5 and v7) to show the moving object path trajectory as shown in below video link rather than just assigning the unique numbers to each object?
> 
> https://www.youtube.com/watch?v=5sya7sl9wWc
> 
> Thank you

ok...
git pull updates of this repo and try this [cmd](https://github.com/bharath5673/StrongSORT-YOLO#draw-object-trajectory)

**Comment by MAli-Farooq** [comment]
sorry my bad its working now ...
