### ISSUE TITLE
can't play saved video when `--save-vid` is used together with `--count`

### ISSUE THREAD

**Issue by bit-scientist** [bharath5673/StrongSORT-YOLO#9]
@bharath5673, I use the following command to save a demo video `python track_v7.py --source demo/video.mp4 --yolo-weights weights/best.pt --save-txt --count --save-vid --draw`, it does save video with its size  (i.e. not empty), but the media players can't play the saved video (VLC, PotPlayer, Windows Media Player, etc.). It has no length information either.
![image](https://user-images.githubusercontent.com/26497571/199460234-42581b90-a370-4882-8d57-d007ae6f9455.png)

However, when I use the above command without `--count`, it works as expected and I can play the saved video, and its size is slightly bigger:
![image](https://user-images.githubusercontent.com/26497571/199460383-32a83f5f-b816-46e7-8bb8-3e83e2419d76.png)

Could you check if this happens on your end?

It'd also be great if you could let me know the exact versions of opencv-python and related packages
Thanks.

**Comment by bharath5673** [comment]
> @bharath5673, I use the following command to save a demo video `python track_v7.py --source demo/video.mp4 --yolo-weights weights/best.pt --save-txt --count --save-vid --draw`, it does save video with its size (i.e. not empty), but the media players can't play the saved video (VLC, PotPlayer, Windows Media Player, etc.). It has no length information either. ![image](https://user-images.githubusercontent.com/26497571/199460234-42581b90-a370-4882-8d57-d007ae6f9455.png)
> 
> However, when I use the above command without `--count`, it works as expected and I can play the saved video, and its size is slightly bigger: ![image](https://user-images.githubusercontent.com/26497571/199460383-32a83f5f-b816-46e7-8bb8-3e83e2419d76.png)
> 
> Could you check if this happens on your end?
> 
> It'd also be great if you could let me know the exact versions of opencv-python and related packages Thanks.

it  should work... please try with other videos

**Comment by tmori2918** [comment]
I also encountered the same error. Changing the video does not cure the error.

**Comment by bit-scientist** [comment]
@bharath5673  I'd kindly ask you look into it in more detail. Because this is happening with other videos as well. Thank you.
